name: lazy_load_refresh_indicator
description: A simple Flutter Widget which provide PullToRefresh and LoadMore functionality. 
version: 2.0.0
homepage: https://github.com/bierbaumtim/lazy_load_refresh_indicator

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
